#!/bin/sh

case "$1" in
    start)
        printf "Starting lmn-3: "
        /bin/LMN-3 &
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    stop)
        printf "Stopping lmn-3: "
        killall LMN-3
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    restart|reload)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?